//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.04 at 03:27:31 PM MESZ 
//


package restserver.schema.account.list;

import javax.xml.bind.annotation.XmlRegistry;
import restserver.schema.account.list.Accountlist.Account;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the restserver.schema.account.list package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: restserver.schema.account.list
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accountlist }
     * 
     */
    public Accountlist createAccountlist() {
        return new Accountlist();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccountlistAccount() {
        return new Account();
    }

}
