//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 05:32:57 PM MESZ 
//


package restserver.schema.account;

import javax.xml.bind.annotation.XmlRegistry;
import restserver.schema.account.Accounts.Account;
import restserver.schema.account.Accounts.Account.Genres;
import restserver.schema.account.Accounts.Account.Genres.Genre;
import restserver.schema.account.Accounts.Account.Wishes;
import restserver.schema.account.Accounts.Account.Wishes.Movie;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the restserver.schema.account package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: restserver.schema.account
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createAccountsAccountWishesMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link Genres }
     * 
     */
    public Genres createAccountsAccountGenres() {
        return new Genres();
    }

    /**
     * Create an instance of {@link Wishes }
     * 
     */
    public Wishes createAccountsAccountWishes() {
        return new Wishes();
    }

    /**
     * Create an instance of {@link Genre }
     * 
     */
    public Genre createAccountsAccountGenresGenre() {
        return new Genre();
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccountsAccount() {
        return new Account();
    }

}
