//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 05:33:38 PM MESZ 
//


package outtake.schema.message;

import javax.xml.bind.annotation.XmlRegistry;
import outtake.schema.message.Messages.Message;
import outtake.schema.message.Messages.Message.Movie;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the restserver.schema.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: restserver.schema.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessagesMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMessagesMessageMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

}
